name: Backport
description: A workflow that allows Backporting PRs via labels etc

on:
  workflow_call:
    inputs:
      BACKPORT_PREFIX:
        description: The prefix to use to identify backport labels - e.g. with a prefix of "Backport to", "Backport to 1.2.3" would backport to "1.2.3" target branch
        required: true
        type: string
      BACKPORT_OPTIONS:
        description: Additional options to pass through to the tool
        required: false
        type: string
    secrets:
      PR_CREATE_TOKEN:
        description: Optional token used for PR creation, defaults to github.token - using a "real" token allows for downstream actions to be triggered - https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/trigger-a-workflow#triggering-a-workflow-from-a-workflow
        required: false

jobs:
  get-current-pr:
    name: Resolve source PR from triggering event
    runs-on: ubuntu-slim
    outputs:
      number: ${{ env.number }}
      merge_commit_sha: ${{ env.merge_commit_sha }}
    steps:
      - name: Extract PR metadata from merged 'pull_request' event
        if: github.event.pull_request.merged && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
        run: |
          # If the action was triggered by labelling a PR, we can simply pull the PR metadata directly from the event
          echo "number=${{ github.event.number }}" >> ${GITHUB_ENV}
          echo "merge_commit_sha=${{ github.event.pull_request.merge_commit_sha }}" >> ${GITHUB_ENV}

      - name: Extract PR metadata from 'push' event
        if: github.event_name == 'push'
        run: |
          source /dev/stdin <<< "$(curl --silent https://raw.githubusercontent.com/hazelcast/github-actions-common-scripts/main/logging.functions.sh)"

          # If the action was triggered by a commit being pushed, we must resolve the PR metadata via the GitHub API

          # Immediately after a commit, sometimes the API returns no results, so poll for valid values
          max_iterations=10
          iteration=0

          while [[ ${iteration} -le ${max_iterations} ]]; do
            response=$(gh api \
              -H "Accept: application/vnd.github+json" \
              /repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/pulls)

            echodebug "API returned: ${response}"

            if [[ $(jq 'length' <<< "${response}") -gt 0 ]]; then
              break
            else
              echo "API returned no results, retrying..."
              iteration=$((iteration + 1))
              sleep 1
            fi
          done

          echo "number=$(jq --raw-output '.[0].number' <<< "${response}")" >> ${GITHUB_ENV}
          echo "merge_commit_sha=${GITHUB_SHA}" >> ${GITHUB_ENV}
        env:
          GH_TOKEN: ${{ github.token }}

  parse-pr:
    if: needs.get-current-pr.outputs.merge_commit_sha != ''
    name: 'Parse PR #${{ needs.get-current-pr.outputs.number }}'
    runs-on: ubuntu-slim
    needs:
      - get-current-pr
    concurrency:
      group: ${{ github.workflow }}-${{ github.repository }}-pr-${{ needs.get-current-pr.outputs.number }}
    outputs:
      backport-branches: ${{ steps.parse-labels.outputs.backport_branches }}
    steps:
      - name: Parsing labels for backports
        id: parse-labels
        run: |
          set -o errexit -o nounset -o pipefail ${RUNNER_DEBUG:+-x}
          source /dev/stdin <<< "$(curl --silent https://raw.githubusercontent.com/hazelcast/github-actions-common-scripts/main/logging.functions.sh)"

          backport_labels=()
          backport_branches=()

          # Iterate through PR labels
          # Re-query via API (inside of `concurrent` block) to ensure we have the latest labels - in case another execution updated any labels while the workflow was being executed
          while IFS= read -r label; do
            if [[ ${label} == "${BACKPORT_PREFIX}"* ]]; then
              backport_labels+=("${label}")

              branch=${label#"${BACKPORT_PREFIX} "}
              echodebug "Extracted \"${branch}\" branch from \"${label}\""
              backport_branches+=("${branch}")
            else
              echodebug "Skipped label \"${label}\" (not a backport)"
            fi
          done < <(gh api \
              -H "Accept: application/vnd.github+json" \
              /repos/${GITHUB_REPOSITORY}/pulls/${{ needs.get-current-pr.outputs.number }} \
              --jq '.labels.[].name')

          function array_to_json() {
            jq --null-input --compact-output '$ARGS.positional' --args "$@"
          }

          json=$(array_to_json "${backport_labels[@]}")
          echo "backport_labels=${json}" >> ${GITHUB_OUTPUT}

          json=$(array_to_json "${backport_branches[@]}")
          echo "backport_branches=${json}" >> ${GITHUB_OUTPUT}
        env:
          GH_TOKEN: ${{ github.token }}
          BACKPORT_PREFIX: ${{ inputs.BACKPORT_PREFIX }}

      - name: Delay
        run: |
          sleep 60

      - name: Remove backport labels (${{ steps.parse-labels.outputs.backport_labels }})
        if: steps.parse-labels.outputs.backport_labels != '[]'
        run: |
          set -o errexit -o nounset -o pipefail ${RUNNER_DEBUG:+-x}

          mapfile -t labels < <(jq --raw-output '.[]' <<< '${{ steps.parse-labels.outputs.backport_labels }}')

          for backport_label in "${labels[@]}"; do
            gh pr edit "${{ needs.get-current-pr.outputs.number }}" \
              --repo ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} \
              --remove-label "${backport_label}"
          done
        env:
          GH_TOKEN: ${{ github.token }}

  backport:
    name: Backport to "${{ matrix.branch }}"
    if: needs.parse-pr.outputs.backport-branches != '[]'
    runs-on: ubuntu-slim
    needs:
      - get-current-pr
      - parse-pr
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(needs.parse-pr.outputs.backport-branches) }}
    steps:
      - name: Delay
        run: |
          sleep 10000000
