name: Test PR

on:
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  test:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
    name: Test (${{matrix.runs-on}})
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - run: ./test_scripts
      - uses: raven-actions/actionlint@v2
        with:
          files: .github/*.yml, .github/*.yaml
