name: Test PR

on:
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  test-scripts:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
    name: Test (${{matrix.runs-on}})
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - run: ./test_scripts
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # https://github.com/raven-actions/actionlint/releases/tag/v2.0.0
      - uses: raven-actions/actionlint@01fce4f43a270a612932cb1c64d40505a029f821
        with:
          files: .github/**/*.yml, .github/**/*.yaml
