name: Test PR

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
    name: Test (${{matrix.runs-on}})
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - run: ./test_scripts
